// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_5YZeyvrnmoU5n4weugxQGt3MCLwpBU',
    appId: '1:399962425027:web:384e02cd74ccf9fd120476',
    messagingSenderId: '399962425027',
    projectId: 'memesiginin',
    authDomain: 'memesiginin.firebaseapp.com',
    storageBucket: 'memesiginin.appspot.com',
    measurementId: 'G-J39DK0S9WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmRIKm3jhYBWJYlCcSDieKDlygPrTcbc',
    appId: '1:399962425027:android:f1630b47ade542a4120476',
    messagingSenderId: '399962425027',
    projectId: 'memesiginin',
    storageBucket: 'memesiginin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7zOkJWhKsKaFUzGqMpRv6ACq0xceEaPA',
    appId: '1:399962425027:ios:62f708c3d00247cf120476',
    messagingSenderId: '399962425027',
    projectId: 'memesiginin',
    storageBucket: 'memesiginin.appspot.com',
    iosClientId: '399962425027-lelkt4mmdsquop6isfok6jhp8kl7oi5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.memegen',
  );
}
